config/routes.rb
Rails.application.routes.draw do
	mount GrapeSwaggerRails::Engine => '/documentation'
  mount API::Base => '/'
  devise_for :users, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :tests
  root 'users#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  extend Enumerize
  scope :student, -> {where(role: :student)}
  has_many :answers, dependent: :destroy
  has_many :tests, foreign_key: 'teacher_id', dependent: :destroy
  validates_presence_of :name
  enumerize :role, in: [:student, :teacher], default: :student

  def generate_api_token
    loop do
      self.api_token = SecureRandom.base64(64)
      break unless self.class.find_by(api_token: api_token)
    end
  end
end

app/controllers/api/v1/users.rb
module API
	module V1
		class Users < API::V1::Default
			resource :users do
				desc "API Sign In" do
          failure [[400, 'Unauthorized', API::V1::Entities::Error]]
          success API::V1::Entities::User
        end
        params do
          requires :email, type: String, desc: "User's email"
          requires :password, type: String, desc: "Password"
        end
        post :sign_in do
          auth = UserAuthenticator.new(params[:email], params[:password])
          unless auth.authenticate
            error!({ message: auth.message, code: 'unauthorized', with: API::V1::Entities::Error }, 400)
          end
          present auth.user, with: API::V1::Entities::User, show_api_key: true
        end

        desc "API Sign Out" do
          failure [[400, 'Unauthorized', API::V1::Entities::Error]]
          headers 'Http-Auth-Token' => { description: 'API Token', required: true }
        end
        delete :sign_out do
          authorize_api!
          current_user.update(api_token: nil)
          present Hash(message: "Sign out sucess!", code: 'sign_out'), with: API::V1::Entities::Success
        end
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.page(params[:page])
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :target => @user } %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :role, :as => :radio_buttons %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title do %>
  Edit User
<% end %>
<div class="page-header">
  <h1>Edit User</h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<% content_for :title do %>
  Users
<% end %>

<header class="header">
  <h1>Users</h1>
  <div class="header-action">
    <%= link_to 'New Student', new_user_path, class: 'btn btn-primary' %>
  </div>
</header>

<div class="table-responsive">
  <div class="row table-action">
    <div class="col-sm-6">
      <div class="table-length">
        <label>Show
          <select class="form-control input-sm">
            <option value="10">10</option>
            <option value="10">20</option>
            <option value="10">50</option>
            <option value="10">100</option>
          </select>
          Entries
        </label>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="table-search pull-right">
        <label>Search 
          <%= form_tag(users_path, {class: 'search-form', method: :get}) do %>
            <%= search_field_tag :search, params[:search], class: "form-control"%>
          <% end %>
        </label>
      </div>
    </div>
  </div>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Created At</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.id, user_path(user) %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= user.created_at %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        user_path(user), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_user_path(user), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @users, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
  Edit User
<% end %>
<div class="page-header">
  <h1>New User</h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong>Role :</strong></dt>
  <dd><%= @user.role %></dd>
  <dt><strong>Email :</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>