config/routes.rb
Rails.application.routes.draw do
	mount GrapeSwaggerRails::Engine => '/documentation'
  mount API::Base => '/'
  devise_for :users, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :tests
  root 'users#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ace" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">ACE Test</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
          <li>
            <%= link_to 'Tests', tests_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="#">Wellcome, <%= current_user.name %></a></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div> <!-- /container -->
    <footer class="footer">
        <div class="container">
          <p class="text-muted">&copy; ACE 2016 - Created by Le Sy Thang</p>
        </div>
      </footer>
  </body>
</html>